### ISSUE TITLE
没地方下载了吗？

### ISSUE THREAD

**Issue by YGQ8988** [xiaope-team/XiaoPE-Download#1]

**Comment by YGQ8988** [comment]
https://xiaope.net/，在维护吗？

**Comment by TheZihanGu** [comment]
> [https://xiaope.net/，在维护吗？](https://xiaope.net/%EF%BC%8C%E5%9C%A8%E7%BB%B4%E6%8A%A4%E5%90%97%EF%BC%9F)

哦哦，之前官网炸了🤷‍♂️
建议还是等一下新版 XiaoPE，将于7月底推出。
或者也可以继续回复要下载链接

**Comment by YGQ8988** [comment]
大佬，官网还没维护好吗？求个最新的下载地址呗。qingygcn@163.com

**Comment by TheZihanGu** [comment]
> 大佬，官网还没维护好吗？求个最新的下载地址呗。[qingygcn@163.com](mailto:qingygcn@163.com)

懒得搞...等会给你发邮件吧。

**Comment by TheZihanGu** [comment]
下载链接：[OneDrive](https://zihanguoffice-my.sharepoint.com/:u:/g/personal/oneindex_a8o_me/Ef9XNNLVu6lDtiVGZy4XTsIBRxKPzohbSVc-EpnfCj7k_g?e=IBnfSs)
目前官网也已经制作完毕并上线。
